import turtle
sb=turtle.Turtle()
sb.pensize(5)
# Body
sb.penup()
sb.goto(-70,-70)
sb.pendown()
sb.fillcolor("yellow")
sb.begin_fill()
sb.forward(200)
sb.left(90)
sb.forward(200)
sb.left(90)
sb.forward(200)
sb.left(90)
sb.forward(200)
sb.end_fill()
# Brown pants
sb.fillcolor("#8B4513")
sb.begin_fill()
sb.forward(40)
sb.left(90)
sb.forward(200)
sb.left(90)
sb.forward(40)
sb.left(90)
sb.forward(200)
sb.left(90)
sb.end_fill()
# Shirt
sb.fillcolor("white")
sb.begin_fill()
sb.forward(20)
sb.left(90)
sb.forward(200)
sb.left(90)
sb.forward(20)
sb.left(90)
sb.forward(200)
sb.end_fill()
sb.penup()
# Tie
sb.left(90)
sb.forward(18)
sb.left(90)
sb.forward(100)
sb.fillcolor("red")
sb.begin_fill()
sb.pencolor("red")
sb.pendown()
sb.circle(7)
sb.end_fill()
sb.penup()
# Eyes
# Eye 1
sb.pencolor("black")
sb.goto(75,50)
sb.pendown()
sb.fillcolor("white")
sb.begin_fill()
sb.circle(25)
sb.end_fill()
sb.fillcolor("black")
sb.penup()
sb.goto(80,60)
sb.begin_fill()
sb.circle(10)
sb.end_fill()
# Eye 2
sb.penup()
sb.pencolor("black")
sb.goto(-15,50)
sb.pendown()
sb.fillcolor("white")
sb.begin_fill()
sb.circle(25)
sb.end_fill()
sb.penup()
sb.goto(-10,60)
sb.fillcolor("black")
sb.begin_fill()
sb.circle(10)
sb.end_fill()
# Smile
sb.penup()
sb.goto(-10,0)
sb.pendown()
sb.pensize(5)
sb.right(90)
sb.fillcolor("red")
sb.begin_fill()
sb.circle(40,180)
sb.left(90)
sb.forward(80)
sb.end_fill()
# Teeths
# Teeth 1
sb.fillcolor("white")
sb.begin_fill()
sb.left(180)
sb.forward(25)
sb.right(90)
sb.forward(15)
sb.left(90)
sb.forward(10)
sb.left(90)
sb.forward(15)
sb.end_fill()
# Teeth 2
sb.fillcolor("white")
sb.begin_fill()
sb.right(90)
sb.forward(10)
sb.right(90)
sb.forward(15)
sb.left(90)
sb.forward(10)
sb.left(90)
sb.forward(15)
sb.end_fill()
# Text
font=('Courier',50,'italic')
sb.penup()
sb.pensize(5)
sb.goto(-300,-300)
sb.write("SpongeBob",font=font)
# Run
turtle.done()